# Numpy: 100 упражнений

### 1. Импорт библиотеки `numpy` под псевдонимом  `np` (★☆☆)

In [1]:
import numpy as np

### 2. Сведения о версии и конфигурации библиотеки (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.21.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

### 3. Создание нулевого вектора размера 10 (★☆☆)

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Как узнать размер `numpy` массива в памяти (★☆☆)

In [4]:
A = np.zeros((10,10))
print("%d bytes" % (A.size * A.itemsize))

800 bytes


### 5. Как получить описание любой функции `numpy` из командной строки? (★☆☆)

```Python
%run `python -c "import numpy; numpy.info(numpy.add)"`
```

In [10]:
np.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### 6. Создать нулевой вектор размера 10, где 5-й элемент равен 1 (★☆☆)

In [11]:
A = np.zeros(10)
A[4] = 1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Создать вектор со значениями в границах [10 49] (★☆☆)

In [13]:
A = np.arange(10, 50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Обращение вектора (первый элемент становится последним) (★☆☆)

In [14]:
A = np.arange(50)
A = A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9. Создание матрицы размера 3x3 со значениями от 0 до 8 (★☆☆)

In [15]:
A = np.arange(9).reshape(3, 3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Нахождение позиций ненулевых элементов в векторе [1,2,0,0,4,0] (★☆☆)

In [17]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


### 11. Создание единичной матрицы (единицы на главной диагонали) размера 3x3 (★☆☆)

In [18]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Создание массива 3x3x3, заполненного случайными значениями (★☆☆)

In [19]:
A = np.random.random((3,3,3))
print(A)

[[[0.87651623 0.11810713 0.88686118]
  [0.04876707 0.57238513 0.75195938]
  [0.91972285 0.51078822 0.48532532]]

 [[0.06210871 0.02758228 0.14191018]
  [0.69538629 0.43556147 0.56102349]
  [0.65093082 0.51044044 0.25530037]]

 [[0.43033732 0.26293007 0.55044828]
  [0.17573627 0.48916478 0.8843296 ]
  [0.198753   0.34073516 0.86855616]]]


### 13. Создание массива 10x10 случайных значений, поиск максимума и минимума (★☆☆)

In [20]:
A = np.random.random((10,10))
Amin, Amax = A.min(), A.max()
print(Amin, Amax)

0.004081779209982317 0.9671513555452446


### 14. Cоздание вектора из 30 случайных значений и поиск среднего арифметического (★☆☆)

In [21]:
A = np.random.random(30)
m = A.mean()
print(m)

0.509097997044518


### 15. Создание вдухмерного массива с 1 на границах и 0 внутри (★☆☆)

In [23]:
A = np.ones((10, 10))
A[1:-1, 1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. Как добавить граинцу (заполненную 0) вокруг существующего массива? (★☆☆)

In [25]:
A = np.ones((5, 5))
A = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(A)

# Using fancy indexing
A[:, [0, -1]] = 0
A[[0, -1], :] = 0
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. Каким будет результат следующих операций? (★☆☆)

In [28]:
0 * np.nan

nan

In [29]:
np.nan == np.nan

False

In [30]:
np.inf > np.nan

False

In [31]:
np.nan - np.nan

nan

In [32]:
np.nan in set([np.nan])

True

In [33]:
0.3 == 3 * 0.1

False

### 18. Создание нулевой матрицы 5x5 с вектром [1,2,3,4] ниже главной диагонали (★☆☆)

In [34]:
A = np.diag(1+np.arange(4), k=-1)
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Создание матрицы 8x8 и ее заполнение в виде шахматной доски (★☆☆)

In [35]:
A = np.zeros((8, 8), dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Узнать положение 100-го элемента в массиве размерности (6, 7, 8) (★☆☆)

In [36]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

### 21. Создание матрицы 8x8 с шахматным рисунком, используя `np.tile` (★☆☆)

In [41]:
A = np.tile(np.array([[0, 1],
                      [1, 0]]), (4, 4))
A

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22. Нормализация рандомной матрицы 5x5 (★☆☆)

In [42]:
A = np.random.random((5, 5))
A = (A - np.mean(A)) / (np.std(A))
print(A)

[[ 0.8399245   0.64821488  0.35676602 -0.14166879 -1.2881403 ]
 [ 0.9609433  -1.02786265 -0.9791282   0.48032411  0.53585355]
 [ 0.91368291 -1.04931272 -1.30808832 -0.58092408 -0.16329805]
 [ 1.72363619 -1.10801457  0.34502675  1.32605828 -0.79204416]
 [-0.99030202 -1.37951479 -0.42207196  1.42753871  1.67240141]]


### 23. Создание кастомного типа данных, описывающего цвет четырьмя байтами (RGBA) (★☆☆)

In [53]:
color = np.dtype([("r", '(1,)ubyte'),
                  ("g", '(1,)ubyte'),
                  ("b", '(1,)ubyte'),
                  ("a", '(1,)ubyte')])

In [54]:
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

### 24. Умножение матрицы 5x3 на матрицу 3x2 (★☆☆)

In [55]:
A = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(A)

# Alternative solution, in Python 3.5 and above
B = np.ones((5, 3)) @ np.ones((3, 2))
print(B)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25. Инвертирование знака у элементов массива со значениями в диапазоне (3, 8) (★☆☆)

In [56]:
A = np.arange(11)
A[(3 < A) & (A < 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### 26. Какой результат выполнения следующего кода? (★☆☆)

In [57]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


### 27. Какие из следующих выражений допустимы? (★☆☆)

In [59]:
A = np.arange(11)

In [60]:
A ** A

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [61]:
2 << A >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [62]:
A <- A

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [63]:
1j * A

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [64]:
A / 1 / 1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
A < A > A

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28. Каким будет результат следующих выражений?

In [66]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-66-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-66-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


### 29. Как округлить в сторону ноля массив чисел с плавающей точкой? (★☆☆)

In [67]:
A = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(A)), A))

# More readable but less efficient
print(np.where(A>0, np.ceil(A), np.floor(A)))

[-2.  1. -1.  7. -5. -2. -6. -5.  6. -8.]
[-2.  1. -1.  7. -5. -2. -6. -5.  6. -8.]


### 30. Как найти общие значения двух массивов (★☆☆)

In [71]:
A1 = np.random.randint(0, 10, 10)
A2 = np.random.randint(0, 10, 10)
print(np.intersect1d(A1, A2))

[0 4 6 9]


### 31. Как избавиться от всех предупреждений и сообщений об ошибке `numpy`? (★☆☆)

In [73]:
# Suicide mode on
defaults = np.seterr(all="ignore")
A = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

### 32. Следующие выражения верны? (★☆☆)

In [76]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-76-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. Как получить даты вчера, сегодня и завтра? (★☆☆)

In [77]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

### 34. Как получить даты всех дней в определенном месяце? (★★☆)

In [78]:
D = np.arange('2020-07', '2020-08', dtype='datetime64[D]')
print(D)

['2020-07-01' '2020-07-02' '2020-07-03' '2020-07-04' '2020-07-05'
 '2020-07-06' '2020-07-07' '2020-07-08' '2020-07-09' '2020-07-10'
 '2020-07-11' '2020-07-12' '2020-07-13' '2020-07-14' '2020-07-15'
 '2020-07-16' '2020-07-17' '2020-07-18' '2020-07-19' '2020-07-20'
 '2020-07-21' '2020-07-22' '2020-07-23' '2020-07-24' '2020-07-25'
 '2020-07-26' '2020-07-27' '2020-07-28' '2020-07-29' '2020-07-30'
 '2020-07-31']


### 35. Как рассчитать ((A+B) * (-A/2)) на месте (без копирования)? (★★☆)

In [80]:
A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

### 36. Извлеките целую часть положительных чисел, используя 4 разных метода (★★☆)

In [81]:
A = np.random.uniform(0,10,10)

print(A - A%1)
print(A // 1)
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

[5. 1. 9. 9. 8. 4. 0. 1. 4. 8.]
[5. 1. 9. 9. 8. 4. 0. 1. 4. 8.]
[5. 1. 9. 9. 8. 4. 0. 1. 4. 8.]
[5 1 9 9 8 4 0 1 4 8]
[5. 1. 9. 9. 8. 4. 0. 1. 4. 8.]


### 37. Cоздать матрицу 5x5 со значениями по строкам от 0 до 4 (★★☆)

In [82]:
A = np.zeros((5, 5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Определить функцию-генератор, создающую последовательность чисел для формирования массива (★★☆)

In [84]:
def generate(n=10):
    for x in range(n):
        yield x

A = np.fromiter(generate(), dtype=float, count=-1)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. Создать вектор из 10 значений из промежутка от 0 до 1 (★★☆)

In [85]:
A = np.linspace(0, 1, 11, endpoint=False)[1:]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Создать вектор из 10 рандомных значений и отсортировать его (★★☆)

In [86]:
A = np.random.random(10)
A.sort()
print(A)

[0.11709048 0.17506782 0.25548032 0.31397915 0.34730353 0.38856961
 0.47761732 0.55475652 0.58845736 0.68454369]


### 41. Как суммировать массив быстрее чем `np.sum`? (★★☆)

In [87]:
A = np.arange(10)
np.add.reduce(A)

45

### 42. Проверить эквивалентность двух рандомных массивов A и B (★★☆)

In [88]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A, B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A, B)
print(equal)

False
False


### 43. Сделать массив неизменным (read-only) (★★☆)

In [89]:
A = np.zeros(10)
A.flags.writeable = False
A[0] = 1

ValueError: assignment destination is read-only

### 44. Рассмотреть матрицу 10x2 c декартовыми координатами (x, y), преобразовать их в полярные (★★☆)

In [90]:
A = np.random.random((10, 2))
X, Y = A[:, 0], A[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.95762604 0.9482505  0.49800135 0.70023265 0.90564965 0.77104906
 1.06765808 0.68251523 0.69866    0.42176397]
[0.23682837 1.33322759 1.25014439 1.22387309 0.34429163 0.36834143
 0.3717954  1.37786546 1.04356944 0.89390642]


### 45. Создать рандомный вектор длины 10 и заменить его максимальное значение 0 (★★☆)

In [91]:
A = np.random.random(10)
A[A.argmax()] = 0
print(A)

[0.34059701 0.51310645 0.         0.64105285 0.8353387  0.31254363
 0.71006729 0.52776165 0.1982578  0.61750236]


### 46. Создать структурированный массив с координатами x и y, покрывающий область [0,1] x [0,1] (★★☆)

In [92]:
A = np.zeros((5, 5), [('x', float),('y', float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47. Для двух массивов A и B построить матрицу Коши $C, c_{ij} = 1 / (a_{i} - b_{j})$  (★★☆)

In [95]:
A = np.arange(8)
B = A + 0.5
C = 1.0 / np.subtract.outer(A, B)
print(np.linalg.det(C)) # определитель матрицы

3638.1636371179666


### 48. Выведите минимальное и максимальное представимые значения для каждого скалярного типа `numpy` (★★☆)

In [103]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49.Как распечатать все значения массива? (★★☆)

In [106]:
A = np.zeros((16, 16))
np.set_printoptions(threshold=float("inf"))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 50. Как найти ближайшее значение (к заданному скаляру) в векторе? (★★☆)

In [107]:
A = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(A-v)).argmin()
print(A[index])

80


### 51. Создать структурированный массив, представляющий позицию (x, y) и цвет (r, g, b) (★★☆)

In [112]:
A = np.zeros(10, [ ('position', [ ('x', '(1,)float'),
                                  ('y', '(1,)float')]),
                   ('color',    [ ('r', '(1,)float'),
                                  ('g', '(1,)float'),
                                  ('b', '(1,)float')])])
print(A)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


### 52. Рассмотрим случайный вектор с формой (100, 2), представляющей координаты, найти расстояние от точки к точке (★★☆)

In [20]:
np.random.seed(0)
A = np.random.random((10, 2))
X, Y = np.atleast_2d(A[:, 0], A[:, 1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

# yet another variant
D2 = np.sqrt(np.add.reduce((A[:,np.newaxis,:] - A[np.newaxis,:,:])**2, axis=-1))
np.array_equal(D, D2)

[[0.         0.1786471  0.14306129 0.20869372 0.53118409 0.30612356
  0.2112843  0.7891329  0.54148195 0.27670999]
 [0.1786471  0.         0.20562852 0.3842079  0.39536284 0.18963685
  0.38229325 0.70162138 0.64973151 0.36942074]
 [0.14306129 0.20562852 0.         0.2462733  0.60040816 0.38621822
  0.31477278 0.66072543 0.44455307 0.41940497]
 [0.20869372 0.3842079  0.2462733  0.         0.73154383 0.50704448
  0.13477076 0.8842009  0.42153982 0.34126404]
 [0.53118409 0.39536284 0.60040816 0.73154383 0.         0.2252094
  0.67115269 0.94052292 1.04491552 0.52073358]
 [0.30612356 0.18963685 0.38621822 0.50704448 0.2252094  0.
  0.45541762 0.84531028 0.82913891 0.34138697]
 [0.2112843  0.38229325 0.31477278 0.13477076 0.67115269 0.45541762
  0.         0.97470248 0.55566014 0.21734021]
 [0.7891329  0.70162138 0.66072543 0.8842009  0.94052292 0.84531028
  0.97470248 0.         0.74722058 1.05495271]
 [0.54148195 0.64973151 0.44455307 0.42153982 1.04491552 0.82913891
  0.55566014 0.747220

True

In [121]:
import scipy.spatial

A = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(A, A)
print(D)

[[0.         0.27413639 0.48775173 0.59841096 0.46859544 0.34137513
  0.13197633 0.28417036 0.29797633 0.19455095]
 [0.27413639 0.         0.46457791 0.37740847 0.69284216 0.36574324
  0.36991218 0.05134812 0.06049842 0.18010461]
 [0.48775173 0.46457791 0.         0.81220105 0.93397829 0.78228725
  0.61548804 0.41606879 0.41302028 0.58268016]
 [0.59841096 0.37740847 0.81220105 0.         0.86967636 0.42742403
  0.63506928 0.41303284 0.41077784 0.41159912]
 [0.46859544 0.69284216 0.93397829 0.86967636 0.         0.44360662
  0.33860262 0.72279815 0.73717512 0.52342704]
 [0.34137513 0.36574324 0.78228725 0.42742403 0.44360662 0.
  0.28850226 0.41397953 0.42546431 0.20138897]
 [0.13197633 0.36991218 0.61548804 0.63506928 0.33860262 0.28850226
  0.         0.39239284 0.40676761 0.228848  ]
 [0.28417036 0.05134812 0.41606879 0.41303284 0.72279815 0.41397953
  0.39239284 0.         0.01440978 0.22242333]
 [0.29797633 0.06049842 0.41302028 0.41077784 0.73717512 0.42546431
  0.40676761 0.01440

### 53. Как преобразовать массив значений с плавающей запятой (32 бита) в целое число (32 бита) на месте? (★★☆)

In [127]:
A = (np.random.rand(10) * 100).astype(np.float32)
B = A.view(np.int32)
B[:] = A
print(A, B)

[6.45e-44 1.25e-43 1.19e-43 7.01e-44 7.57e-44 1.19e-43 6.87e-44 4.62e-44
 4.34e-44 7.43e-44] [46 89 85 50 54 85 49 33 31 53]


### 54. Как прочитать следующий файл? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [133]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
A = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(A)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


### 55. Что эквивалентно `enumerate` для массивов `numpy`? (★★☆)

In [135]:
A = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(A):
    print(index, value)

for index in np.ndindex(A.shape):
    print(index, A[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56. Сгенерировать универсальный двумерный гауссовский массив (★★☆)

In [136]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2))) # Gaussian distribution's formula
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57. Как случайным образом разместить p элементов в 2D-массиве? (★★☆)

In [137]:
n = 10
p = 3
A = np.zeros((n, n))
np.put(A, np.random.choice(range(n*n), p, replace=False), 1)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 58. Вычтите среднее значение каждой строки матрицы (★★☆)

In [138]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.13184542 -0.07835162 -0.30382932  0.43339266 -0.23769709 -0.26759143
   0.23953311  0.43760362 -0.20309194 -0.15181339]
 [ 0.31884965 -0.421197    0.20702889  0.28501627 -0.37865273  0.35697929
  -0.61475449 -0.27577944  0.29232485  0.23018471]
 [ 0.09555229  0.22789364 -0.26410151 -0.32279962  0.49493431 -0.2002137
   0.04559728  0.11864869 -0.06460262 -0.13090877]
 [-0.05851964  0.0123607  -0.08433769  0.1996323   0.36109895 -0.55105744
   0.23250948 -0.3278195   0.35502633 -0.13889349]
 [-0.14469864 -0.39502455 -0.16264486  0.133854   -0.4649972   0.17853462
  -0.17742807  0.42660923  0.13371089  0.47208459]]


### 59. Как отсортировать массив по n-му столбцу? (★★☆)

In [141]:
A = np.random.randint(0, 10, (3,3))
print(A)
print(A[A[:, 1].argsort()])

[[4 7 6]
 [9 3 9]
 [4 4 7]]
[[9 3 9]
 [4 4 7]
 [4 7 6]]


### 60. Как определить, есть ли в 2D-массиве нулевые столбцы? (★★☆)

In [143]:
A = np.random.randint(0, 3, (3,10))
print(A, (~A.any(axis=0)).any())

[[0 0 1 0 2 2 1 1 1 1]
 [1 2 0 2 1 0 0 1 0 2]
 [2 1 2 1 2 1 2 1 2 1]] False


### 61. Найдите ближайшее значение для заданного значения в массиве (★★☆)

In [144]:
A = np.random.uniform(0, 1, 10)
a = 0.5
m = A.flat[np.abs(A - a).argmin()]
print(m)

0.4942909456182839


### 62. Как вычислить сумму двух массивов с формой (1, 3) и (3, 1) с помощью итератора? (★★☆)

In [150]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 63. Создать класс массива с атрибутом `name` (★★☆)

In [151]:
class NamedArray(np.ndarray):
    
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

A = NamedArray(np.arange(10), "range_10")
print(A.name)

range_10


### 64. Как добавить 1 к каждому элементу вектора, проиндексированному другим вектором? (★★★)

In [156]:
A = np.ones(10)
I = np.random.randint(0, len(A), 20)
A += np.bincount(I, minlength=len(A))
print(A)

# Another solution
A = np.ones(10)
np.add.at(A, I, 1)
print(A)

[2. 3. 2. 2. 3. 5. 4. 4. 3. 2.]
[2. 3. 2. 2. 3. 5. 4. 4. 3. 2.]


### 65. Как собрать элементы вектора (A) в массив (F) на основе списка индексов (I)? (★★★)

In [158]:
A = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, A)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### 66. Рассматривая (w, h, 3) изображение (dtype=ubyte), вычислите количество уникальных цветов (★★★)

In [160]:
w = h = 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
F = I[..., 0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

4


### 67. Как получить сумму сразу по двум последним осям в четырехмерном массиве? (★★★)

In [166]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
s = A.sum(axis=(-2, -1))
print(s)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
s = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(s)

[[61 37 55 53]
 [52 63 72 43]
 [58 65 57 59]]
[[61 37 55 53]
 [52 63 72 43]
 [58 65 57 59]]


### 68. Как вычислить средние подмножества D, используя вектор S того же размера, описывающий индексы подмножества? (★★★)

In [167]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.54576427 0.67370024 0.58990371 0.50616945 0.43754759 0.57098981
 0.55012468 0.32447483 0.58318224 0.35110601]
0    0.545764
1    0.673700
2    0.589904
3    0.506169
4    0.437548
5    0.570990
6    0.550125
7    0.324475
8    0.583182
9    0.351106
dtype: float64


### 69. Как получить диагональ скалярного произведения матриц A и B? (★★★)

In [171]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij, ji->i", A, B)

array([1.8247868 , 1.38187596, 0.70429714, 1.23012355, 1.75207777])

### 70. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [174]:
A = np.array([1, 2, 3, 4, 5])
n = 3
A0 = np.zeros(len(A) + (len(A)-1) * n)
A0[::n+1] = A
print(A0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### 71. Как массив размерности (5,5,3) умножить на массив размерности (5,5)? (★★★)

In [178]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:, :, np.newaxis])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### 72. Как поменять местами две строки массива? (★★★)

In [180]:
A = np.arange(25).reshape(5, 5)
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 73. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти набор уникальных отрезков прямых, составляющих все треугольники (★★★)

In [181]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 5, 27) ( 5, 39) ( 5, 57) ( 5, 72) (13, 47) (13, 49) (19, 20) (19, 45)
 (20, 45) (22, 47) (22, 93) (25, 75) (25, 85) (27, 72) (34, 86) (34, 91)
 (37, 71) (37, 73) (39, 57) (46, 57) (46, 77) (47, 49) (47, 93) (57, 77)
 (67, 69) (67, 90) (69, 90) (71, 73) (75, 85) (86, 91)]


### 74. Дан отсортированный массив C, как создать массив A, такой что `np.bincount(A) == C`? (★★★)

In [187]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### 75. Как вычислить средние значения с помощью скользящего окна по массиву? (★★★)

In [193]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

A = np.arange(20)
print(moving_average(A, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### 76. Рассмотрим одномерный массив Z, построим двумерный массив, первая строка которого имеет вид (Z[0], Z[1], Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть ( Z[-3], Z[-2], Z[-1]) (★★★)

In [194]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### 77. Как инвертировать логическое значение или изменить знак числа с плавающей точкой на месте? (★★★)

In [195]:
A = np.random.randint(0, 2, 100)
np.logical_not(A, out=A)
print(A)
A = np.random.uniform(-1.0, 1.0, 100)
np.negative(A, out=A)
print(A)

[0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 0 1 1
 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 1 0 1 1]
[ 0.82788237 -0.28469768  0.0800749  -0.16262822 -0.93183303 -0.07459081
  0.92301131 -0.3949941   0.78339462 -0.81697694 -0.44413409 -0.44447261
  0.15188819  0.83710803  0.43955204 -0.08532102  0.53348164  0.70904658
 -0.66311848  0.17065951 -0.20506096 -0.14510722 -0.69911753 -0.80031511
  0.04623199  0.37371101  0.40793923 -0.52024996 -0.05817242  0.77376692
  0.62724588 -0.44426431  0.16018453 -0.97755012 -0.10546672  0.02550625
 -0.03852311  0.15096733  0.81623003  0.43872926 -0.44875709  0.2853553
 -0.86769276  0.86029727 -0.23297394 -0.50914696  0.16595375 -0.08434645
  0.50261075  0.09067257  0.25625401  0.35355324 -0.27930202 -0.79134729
 -0.68790551 -0.39979537  0.89982758  0.07823036  0.34106465  0.85230125
  0.45960007  0.78283383 -0.29510343 -0.09473076 -0.53246558 -0.571

### 78. Рассмотрим 2 набора точек $P0, P1$, описывающих прямые, и точку $p$, как вычислить расстояние от $p$ до каждой прямой $i(P0[i], P1[i])$? (★★★)

In [21]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p  = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[ 3.61430921  9.9246322  10.61985779  1.05519013  4.16920097 10.50087143
 10.80723219  1.3131153  10.14085336  2.17539353]


### 79. Рассмотрим 2 набора точек  $P0, P1$, описывающих линии, и набор точек $P$, как вычислить расстояние от каждой точки $j(P[j])$ до каждой линии $i(P0[i], P1[i])$? (★★★)

In [199]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))

[[ 0.81940918  2.13094365 11.96199223  6.79171687 11.85099291  0.11326521
   9.36767983  1.98775448 12.42463853 17.78222182]
 [10.23812491 12.346744    3.20214879 11.35115238  2.0635875  10.85945416
   0.89888681  8.01418765  4.98524911 13.97876374]
 [ 8.76244678  6.31659525  2.03653668 13.04865686  8.07241145  9.43341711
   5.18003442  7.13487444 10.55112892 18.61861154]
 [ 7.73934282  1.47587639 11.51436422  3.18947581  3.44006131  7.09857556
   1.23759987  9.65502109  2.94485923  7.38955906]
 [ 4.76180496  9.93050824  3.85667249  4.52547658  4.42378637  4.18648227
   6.76211346  7.46813722  4.14264535  1.771201  ]
 [ 9.21211158  6.16043725  8.34621978  7.51784033  2.84485165  8.62188694
   4.99341866 11.72220545  3.44367303  1.22805707]
 [ 2.59850576  9.00626685  3.83710427  1.51957866  2.02768784  2.00464639
   4.45411952  5.09380637  1.40597584  4.81512435]
 [ 3.87576321 10.33547966  0.5657566   5.1719792   0.44383231  4.48680247
   2.25242352  1.55685012  2.21429978  9.79544362]


### 80. Рассмотрим произвольный массив, напишите функцию, которая извлекает подчасть фиксированной формы и центрируется на заданном элементе (★★★)

In [205]:
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2) + Rs%2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 0 1 1 0 6 8 9 8 4]
 [6 6 2 4 8 6 0 9 3 6]
 [3 4 5 7 7 6 0 2 2 2]
 [4 0 5 6 9 3 3 3 6 9]
 [9 9 6 0 2 9 4 7 0 7]
 [1 6 6 3 6 9 1 8 2 5]
 [1 4 9 3 4 3 9 8 5 8]
 [1 2 8 0 6 3 5 7 5 5]
 [7 6 2 5 3 0 3 1 3 8]
 [6 6 3 7 2 4 1 3 7 8]]
[[0 0 0 0 0]
 [0 3 0 1 1]
 [0 6 6 2 4]
 [0 3 4 5 7]
 [0 4 0 5 6]]


<ipython-input-205-46f0e59d5fb8>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


### 81. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2, 3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [206]:
Z = np.arange(1, 15, dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. Вычислить ранг матрицы (★★★)

In [211]:
A = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(A) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


### 83. Как найти наиболее часто встречающееся значение в массиве?

In [26]:
A = np.random.randint(0, 10, 50)
print(np.bincount(A).argmax())

3


### 84. Извлечь все смежные блоки 3x3 из случайной матрицы 10x10 (★★★)

In [215]:
Z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(Z, C, sep='\n')

[[2 2 4 3 1 4 3 1 4 2]
 [3 4 1 3 1 2 4 2 3 1]
 [1 1 3 0 1 3 0 3 4 1]
 [2 3 1 4 4 1 4 3 2 1]
 [4 1 1 1 0 0 0 3 1 3]
 [2 3 4 1 3 4 3 2 2 3]
 [1 3 1 4 2 1 4 1 4 3]
 [0 3 4 4 4 4 1 4 3 1]
 [2 0 1 0 4 0 2 2 0 2]
 [0 2 2 2 3 1 2 1 4 4]]
[[[[2 2 4]
   [3 4 1]
   [1 1 3]]

  [[2 4 3]
   [4 1 3]
   [1 3 0]]

  [[4 3 1]
   [1 3 1]
   [3 0 1]]

  [[3 1 4]
   [3 1 2]
   [0 1 3]]

  [[1 4 3]
   [1 2 4]
   [1 3 0]]

  [[4 3 1]
   [2 4 2]
   [3 0 3]]

  [[3 1 4]
   [4 2 3]
   [0 3 4]]

  [[1 4 2]
   [2 3 1]
   [3 4 1]]]


 [[[3 4 1]
   [1 1 3]
   [2 3 1]]

  [[4 1 3]
   [1 3 0]
   [3 1 4]]

  [[1 3 1]
   [3 0 1]
   [1 4 4]]

  [[3 1 2]
   [0 1 3]
   [4 4 1]]

  [[1 2 4]
   [1 3 0]
   [4 1 4]]

  [[2 4 2]
   [3 0 3]
   [1 4 3]]

  [[4 2 3]
   [0 3 4]
   [4 3 2]]

  [[2 3 1]
   [3 4 1]
   [3 2 1]]]


 [[[1 1 3]
   [2 3 1]
   [4 1 1]]

  [[1 3 0]
   [3 1 4]
   [1 1 1]]

  [[3 0 1]
   [1 4 4]
   [1 1 0]]

  [[0 1 3]
   [4 4 1]
   [1 0 0]]

  [[1 3 0]
   [4 1 4]
   [0 0 0]]

  [[3 0 3]
   [1 4 3]
   [0 0 

### 85. Создайте подкласс 2D-массива так, чтобы Z[i, j] == Z [j, i] (★★★)

In [216]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
print(S)

[[ 8  8 11 17 14]
 [ 8  7  5  8 11]
 [11  5  0 42  4]
 [17  8 42  5  7]
 [14 11  4  7  7]]


### 86. Рассмотрим набор из p матриц формы (n, n) и набор из p векторов формы (n, 1). Как вычислить  сумму произведений матрицы p? (★★★)

In [217]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


### 87. Рассмотрим массив 16x16, как получить блок-сумму (размер блока 4x4)? (★★★)

In [220]:
Z = np.ones((16, 16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88. Как реализовать «Игру Жизни», используя множество массивов? (★★★)

In [221]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

### 89. Как получить n наибольших значений массива? (★★★)

In [222]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print(Z[np.argsort(Z)[-n:]])

# Fast
print(Z[np.argpartition(-Z, n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9995 9997 9999]


### 90. Для произвольного количества векторов построить декартово произведение (все комбинации каждого элемента) (★★★)

In [226]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### 91. Как создать массив записей из обычного массива? (★★★)

In [232]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### 92. Рассмотрим большой вектор Z, вычислим Z в степени 3, используя 3 разных метода (★★★)

In [233]:
x = np.random.rand(int(5e7))

%timeit np.power(x, 3)
%timeit x * x * x
%timeit np.einsum('i, i, i->i', x, x, x)

5.89 s ± 872 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
889 ms ± 64.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.19 s ± 414 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 93. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, которые содержат элементы каждой строки B независимо от порядка элементов в B? (★★★)

In [234]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[2 4]


### 94. Рассматривая матрицу 10x3, извлеките строки с неравными значениями (например, [2,2,3]) (★★★)

In [237]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1), :]
print(U)

[[1 2 2]
 [4 2 4]
 [2 2 0]
 [0 1 2]
 [4 0 1]
 [4 0 2]
 [3 0 0]
 [3 1 4]
 [4 3 1]
 [1 3 2]]
[[1 2 2]
 [4 2 4]
 [2 2 0]
 [0 1 2]
 [4 0 1]
 [4 0 2]
 [3 0 0]
 [3 1 4]
 [4 3 1]
 [1 3 2]]
[[1 2 2]
 [4 2 4]
 [2 2 0]
 [0 1 2]
 [4 0 1]
 [4 0 2]
 [3 0 0]
 [3 1 4]
 [4 3 1]
 [1 3 2]]


### 95. Преобразование целочисленного вектора в матричное двоичное представление (★★★)

In [238]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print(B[:, ::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### 96.  Как извлечь только уникальные строки из двухмерного массива? (★★★)

In [239]:
Z = np.random.randint(0, 2,(6, 3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


### 97. Рассматривая 2 вектора A и B, запишите эквивалент einsum для функций inner, outer, sum и mul (★★★)

In [240]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

np.einsum('i->', A)        # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)     # np.inner(A, B)
np.einsum('i,j->ij', A, B) # np.outer(A, B)

array([[0.14363696, 0.43354051, 0.33807696, 0.26614485, 0.45154378,
        0.60535807, 0.64059405, 0.08953195, 0.40726781, 0.46382325],
       [0.11429415, 0.34497488, 0.26901306, 0.21177556, 0.35930036,
        0.48169276, 0.50973058, 0.07124196, 0.32406928, 0.36907133],
       [0.03946371, 0.11911362, 0.09288537, 0.07312229, 0.12405995,
        0.16631985, 0.1760008 , 0.02459857, 0.1118953 , 0.12743369],
       [0.02955417, 0.08920357, 0.06956137, 0.0547609 , 0.09290785,
        0.12455607, 0.13180608, 0.01842174, 0.0837978 , 0.09543443],
       [0.15100432, 0.45577746, 0.35541743, 0.27979582, 0.47470414,
        0.6364078 , 0.67345108, 0.09412418, 0.42815718, 0.48761345],
       [0.07082992, 0.21378647, 0.16671171, 0.13124072, 0.2226642 ,
        0.29851274, 0.31588822, 0.04414978, 0.20083094, 0.22871942],
       [0.09055675, 0.27332812, 0.21314257, 0.16779255, 0.28467838,
        0.38165149, 0.40386622, 0.05644594, 0.25676434, 0.29242005],
       [0.09646803, 0.29117017, 0.2270558

### 98. Имея путь, описанный двумя векторами (X, Y), как отсортировать его, используя эквидистантные образцы (★★★)?

In [244]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2) ** .5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

### 99. Для целого числа n и двумерного массива X выберите строки, которые можно интерпретировать как отрисовки из полиномиального распределения с n степенями, то есть строки, которые содержат только целые числа и сумма которых равна n. (★★★)

In [245]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


### 100. Вычислить бутсрапированный 95% доверительный интервал для среднего значения одномерного массива X (выполнить повторную выборку элементов массива с заменой N раз, вычислить среднее значение каждой выборки, а затем вычислить процентили по средним). (★★★)

In [246]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.06523806  0.37940603]


### 101. Cпираль змейкой NxN заданного размера. (★★★)

In [53]:
def spiralize(n: int) -> np.array:
    if n == 1: return np.asarray([[1]])
    if n == 2: return np.asarray([[1,1],[0,1]])
    A = np.zeros((n, n))
    A[[0,-1],:] = 1
    A[:,-1] =  1
    A[2:,:-2] = spiralize(n-2)[::-1,::-1]
    
    return A.astype(int)

In [54]:
spiralize(10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])