# Элементы линейной алгебры на Python

In [2]:
import math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## ОПЕРАЦИИ НАД МАТРИЦАМИ И ИХ СВОЙСТВА

### Возведение матрицы в степень

Возвести $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\ 
\end{pmatrix}
\end{equation*}$ в третью степень

In [8]:
A = np.array([[1, 3], [2, 4]])
np.linalg.matrix_power(A, 3)

array([[ 37,  81],
       [ 54, 118]])

### Транспонирование матрицы

Транспонировать матрицу $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\ 
\end{pmatrix}
\end{equation*}$

In [7]:
A.transpose()

array([[1, 2],
       [2, 3]])

Вычислить значения многочлена $F(x) = 2x^3 - x + 5$ от матрицы $\begin{equation*}
A = 
\begin{pmatrix}
-1 & 2 \\
0 & 2 \\ 
\end{pmatrix}
\end{equation*}$

In [9]:
A = np.array([[-1, 0], [2, 2]])
np.linalg.matrix_power(A, 3) - A + 5

array([[ 5,  5],
       [ 9, 11]])

Вычислить определитель матрицы $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 & 3 & 4 \\
2 & 1 & 3 & 4 \\ 
3 & 1 & 2 & 4 \\
4 & 3 & 2 & 1 \\
\end{pmatrix}
\end{equation*}$

In [14]:
A = np.array([[1, 2, 3, 4], 
              [2, 1, 3, 4],
              [3, 1, 2, 4],
              [4, 3, 2, 1]])
np.linalg.det(A)

-30.000000000000004

Вычислить обратную матрицу $\begin{equation*}
A = 
\begin{pmatrix}
1 & -1 & 1 \\
2 & 1 & 1 \\ 
1 & 1 & 2 \\
\end{pmatrix}
\end{equation*}$

In [17]:
A = np.array([[1, -1, 1], 
              [2, 1, 1],
              [1, 1, 2]])

np.linalg.inv(A)

array([[ 0.2,  0.6, -0.4],
       [-0.6,  0.2,  0.2],
       [ 0.2, -0.4,  0.6]])

Решить матричное уравнение $A X = B$

$\begin{equation*}A = 
\begin{pmatrix}
3 & 1 \\
-3 & 1 \\ 
\end{pmatrix}
\end{equation*}$,
$\begin{equation*}B = 
\begin{pmatrix}
9 & 5 \\
-3 & -1 \\ 
\end{pmatrix}
\end{equation*}$

Матрицу `X` находим путем произведения обратной матрицы $A^-1$ и $B$

In [18]:
A = np.array([[3, 1], 
              [-3, 1]])

B = np.array([[9, 5], 
              [-3, -1]])

np.dot(np.linalg.inv(A), B)

array([[2., 1.],
       [3., 2.]])

Вычислить ранг матрицы $\begin{equation*}
A = 
\begin{pmatrix}
0 & -1 & 3 & 0 & 2 \\
2 & -4 & 1 & 5 & 3 \\ 
-4 & 5 & 7 & -10 & 0 \\
-2 & 1 & 8 & -5 & 3 \\
\end{pmatrix}
\end{equation*}$

In [21]:
A = np.array([[0, -1, 3, 0, 2], 
              [2, -4, 1, 5, 3],
              [-4, 5, 7, -10, 0],
              [-2, 1, 8, -5, 3]])

np.linalg.matrix_rank(A)

2

## СИСТЕМЫ ЛИНЕЙНЫХ УРАВНЕНИЙ (СЛУ)

$${\displaystyle {\begin{cases}a_{11}x_{1}+a_{12}x_{2}+\dots +a_{1n}x_{n}=b_{1}\\a_{21}x_{1}+a_{22}x_{2}+\dots +a_{2n}x_{n}=b_{2}\\\dots \\a_{m1}x_{1}+a_{m2}x_{2}+\dots +a_{mn}x_{n}=b_{m}\\\end{cases}}}$$

где $a_{ij}$ и $b_{j}$ — произвольные числа, называемые коэффициентами при меременных $x_{1}, x_{2} \dots x_{n}$ и свободными членами. Матричная форма записи имеет вид $A = XB$, где

$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{pmatrix}$ — матрица коэффициентов при неизвестных,

$X = \begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{pmatrix}$ — матрица из неизвестных системы,

$B =
\begin{pmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{pmatrix}$ — матрица из свободных членов.

Решением системы `m` линейных уравнений с `n` переменными называют упорядоченный набор чисел, при подстановке которых в каждое уравнение системы вместо соответствующих переменных получают верное равенство. Как доказывает <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9A%D1%80%D0%BE%D0%BD%D0%B5%D0%BA%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%9A%D0%B0%D0%BF%D0%B5%D0%BB%D0%BB%D0%B8">Теорема Кронекера-Капелли</a>, СЛУ могут иметь одно решение, бесконечное множество решений, так и не иметь решения.

Рассмотрим случай, когда система имеет единственное решение. Это значит, что матрицв системы невырожднная, т.е. ее определитель не равен нулю, и эту систему можно решать по правилу <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0">Крамера</a> или методом обратной матрицы.

${\displaystyle {\begin{cases}3x_{1}-x_{2}+x_{3}=5\\
x_{1}-x_{2}-x_{3}=3\\
5x_{1}-3x_{2}-x_{3}=10\\\end{cases}}}$

Для решения системы воспользуемся функцией <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html">numpy.linalg.solve</a>. Функция принимает два параметра:
 - матрица коэффициентов перед переменными
 - вектор свободных членов

In [28]:
A = np.array([[3, -1, 1], 
              [1, -1, 1],
              [5, -3, -1,]])

B = np.array([3, 11, 8])

X = np.linalg.solve(A, B)

for i, x in enumerate(X, 1):
    print(f'x{i} = {x:.2f}')

x1 = -4.00
x2 = -10.75
x3 = 4.25


Определитель основной матрицы системы не равен нулю, мы получили единственное решение, хотя и не целочисленное.

In [29]:
np.linalg.det(A)

7.999999999999998

### Решение системы линейных уравнений $AX = B$ методом обратной матрицы

Для этого:
   1. вычислим определитель матрицы $A$. Если определитель равен нулю, то конец решения. Система имеет бесконечное множество решений.
   2. при определителе отличном от нуля, через алгебраические дополнения находится обратная матрица $A^{-1}$.
   3. вектор решения $X = \{x_{1}, x_{2} \dots x_{n}\}$ получается умолжением обратной матрицы на вектор результата $B$.

__Решить СЛУ методом обратной матрицы__

${\displaystyle{\begin{cases}2x_{1}-x_{2}-2x_{3}=-3\\
x_{1}-2x_{2}+x_{3}=5\\
3x_{1}+x_{2}-x_{3}=0\\\end{cases}}}$

In [34]:
A = np.array([[2, 1, -2], 
              [1, -2, 1],
              [3, 1, -1,]])

B = np.array([-3, 5, 0])

det = np.linalg.det(A)
if det == 0:
    print('Система имеет бесконечное множество решений, \
           определитель матрицы равен 0')
else:
    AI = np.linalg.inv(A)
    X = np.dot(AI, B)
    print(f'Решение системы {X}')

Решение системы [ 1. -1.  2.]


### Решение системы линейных уравнений $AX = B$ с использованием метода Крамера

Если определитель матрицы системы не равен нулю, ее можно решить по <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0">правилу Крамера</a>. Для этого находят определитель матрицы системы и делят на него определители, полученные заменой $i$-го столбца матрицы системы на столбец свободных членов. Эти отношения и будуи составлять решение системы. Оно будет единственным.

__Решить СЛУ методом Крамера__

${\displaystyle{\begin{cases}2x_{1}-x_{2}-2x_{3}=-3\\
x_{1}-2x_{2}+x_{3}=5\\
3x_{1}+x_{2}-x_{3}=0\\\end{cases}}}$

In [40]:
det = np.linalg.det(A)
if det == 0:
    print('определитель матрицы равен 0, \
          система имеет бесконечное множество решений')
else:
    s0, s1, s2 = A[:,0], A[:,1], A[:,2]
    a1 = np.column_stack((B, s1, s2))
    a2 = np.column_stack((s0, B, s2))
    a3 = np.column_stack((s0, s1, B))
    X = [d / det for d in map(np.linalg.det, (a1, a2, a3))]
    print(f'Решение системы {X}')

Решение системы [0.9999999999999996, -1.0, 2.0000000000000004]


Рассмотрим пример системы, которая имеет бесконечное множество решений.

### Этапы решения

  1. Найти определитель матрицы системы
  2. Если он не равен нулю, вывести решения с помошью `np.linalg.solve(A, B)`
  3. Иначе сравниваем ранги расширенной и основной матриц системы и используем <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9A%D1%80%D0%BE%D0%BD%D0%B5%D0%BA%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%9A%D0%B0%D0%BF%D0%B5%D0%BB%D0%BB%D0%B8">теорему Кронекера-Капелли</a>.
  
__Решить СЛУ__

${\displaystyle{\begin{cases}x_{1}+2x_{2}-x_{3}=7\\
2x_{1}-3x_{2}+x_{3}=3\\
4x_{1}+x_{2}-x_{3}=16\\\end{cases}}}$

In [63]:
A = np.array([[1, 2, -1], 
              [2, -3, 1],
              [4, 1, -1,]])

B = np.array([7, 3, 16])

det = np.linalg.det(A)

B1 = B.reshape((1, -1)) # B[np.newaxis, :]
AB = np.vstack((A, B1))

if det:
    X = np.linalg.solve(A, B)
    print('Единственное решение', X)
else:
    rank_a = np.linalg.matrix_rank(A) 
    rank_ab = np.linalg.matrix_rank(AB) 
    if rank_a == rank_ab:
        print('Система имеет бесконечное множество \
                               решений и частное', X)
    else:
        print('Система не имеет решений')

Система не имеет решений


# Элементы аналитической геометрии

## Векторы на плоскости и в пространстве. Операции над векторами.

Вектором на плостости и в пространстве называютмножество сонаправленных отрезков, имеющих одиноковую длину. Обозначают векторы малыми латинскими буквами со стрелкой ${\vec {a}}$. Если даны координаты начала и конца вектора, то чтобы найти координаты вектора, нужно из координат конца вычесть координаты начала. Если $A = (x_{1};y_{1}), B = (x_{2};y_{2})$, то ${\overrightarrow {AB}} = (x_{2}-x_{1};y_{2}-y_{1})$, а длина вектора $|{\overrightarrow  {AB}}| = |AB| = {\sqrt {(x_{2}-x_{1})^{2}+(y_{2}-y_{1})^{2}}}$.

Векторы линейно зависимые, если один из них можно представить как линейную комбинацию других.

### Примеры решений

1) Даны вектор $a(5;1)$ и точка $A(-2;3)$. Найти координаты точки $B$, такой, что ${\vec {a}} = AB$

In [67]:
a = np.array([5, 1])
A = np.array([-3, 3])
B = a + A; B

array([2, 4])

2) Найти вектор — результат векторного произведения векторов $a = (1;3;-1), b = (2;-2;1)$ и его длину.

Запишем вектор ${\vec {с}}$ через разлодение по базисным ортам $i, j, k$ и найдем его длину с помощью функции `np.linalg.norm`.

${\vec {с}} = {\displaystyle [{\vec {a}},\;{\vec {b}}]={\begin{vmatrix}\mathbf {i} &\mathbf {j} &\mathbf {k} \\a_{x}&a_{y}&a_{z}\\b_{x}&b_{y}&b_{z}\end{vmatrix}}}$

In [92]:
a = np.array([[1, 3, -1],
              [2, -2, 1]])

i, j, k = [a[:,x] for x in range(3)]

a1 = np.column_stack((j, k))
a2 = np.column_stack((i, k))
a3 = np.column_stack((i, j))

c = [*map(np.linalg.det, (a1, a2, a3))]

print('c = ({:.1f})i + ({:.1f})j + ({:.1f})k\n\
Длина векторного произведения n = {}'.format(*c, np.linalg.norm(c)))

c = (1.0)i + (3.0)j + (-8.0)k
Длина векторного произведения n = 8.602325267042625
