# Элементы линейной алгебры на Python

In [2]:
import math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## ОПЕРАЦИИ НАД МАТРИЦАМИ И ИХ СВОЙСТВА

### Возведение матрицы в степень

Возвести $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\ 
\end{pmatrix}
\end{equation*}$ в третью степень

In [8]:
A = np.array([[1, 3], [2, 4]])
np.linalg.matrix_power(A, 3)

array([[ 37,  81],
       [ 54, 118]])

### Транспонирование матрицы

Транспонировать матрицу $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\ 
\end{pmatrix}
\end{equation*}$

In [7]:
A.transpose()

array([[1, 2],
       [2, 3]])

Вычислить значения многочлена $F(x) = 2x^3 - x + 5$ от матрицы $\begin{equation*}
A = 
\begin{pmatrix}
-1 & 2 \\
0 & 2 \\ 
\end{pmatrix}
\end{equation*}$

In [9]:
A = np.array([[-1, 0], [2, 2]])
np.linalg.matrix_power(A, 3) - A + 5

array([[ 5,  5],
       [ 9, 11]])

Вычислить определитель матрицы $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 & 3 & 4 \\
2 & 1 & 3 & 4 \\ 
3 & 1 & 2 & 4 \\
4 & 3 & 2 & 1 \\
\end{pmatrix}
\end{equation*}$

In [14]:
A = np.array([[1, 2, 3, 4], 
              [2, 1, 3, 4],
              [3, 1, 2, 4],
              [4, 3, 2, 1]])
np.linalg.det(A)

-30.000000000000004

Вычислить обратную матрицу $\begin{equation*}
A = 
\begin{pmatrix}
1 & -1 & 1 \\
2 & 1 & 1 \\ 
1 & 1 & 2 \\
\end{pmatrix}
\end{equation*}$

In [17]:
A = np.array([[1, -1, 1], 
              [2, 1, 1],
              [1, 1, 2]])

np.linalg.inv(A)

array([[ 0.2,  0.6, -0.4],
       [-0.6,  0.2,  0.2],
       [ 0.2, -0.4,  0.6]])

Решить матричное уравнение $A X = B$

$\begin{equation*}A = 
\begin{pmatrix}
3 & 1 \\
-3 & 1 \\ 
\end{pmatrix}
\end{equation*}$,
$\begin{equation*}B = 
\begin{pmatrix}
9 & 5 \\
-3 & -1 \\ 
\end{pmatrix}
\end{equation*}$

Матрицу `X` находим путем произведения обратной матрицы $A^-1$ и $B$

In [18]:
A = np.array([[3, 1], 
              [-3, 1]])

B = np.array([[9, 5], 
              [-3, -1]])

np.dot(np.linalg.inv(A), B)

array([[2., 1.],
       [3., 2.]])

Вычислить ранг матрицы $\begin{equation*}
A = 
\begin{pmatrix}
0 & -1 & 3 & 0 & 2 \\
2 & -4 & 1 & 5 & 3 \\ 
-4 & 5 & 7 & -10 & 0 \\
-2 & 1 & 8 & -5 & 3 \\
\end{pmatrix}
\end{equation*}$

In [21]:
A = np.array([[0, -1, 3, 0, 2], 
              [2, -4, 1, 5, 3],
              [-4, 5, 7, -10, 0],
              [-2, 1, 8, -5, 3]])

np.linalg.matrix_rank(A)

2

## СИСТЕМЫ ЛИНЕЙНЫХ УРАВНЕНИЙ (СЛУ)

$${\displaystyle {\begin{cases}a_{11}x_{1}+a_{12}x_{2}+\dots +a_{1n}x_{n}=b_{1}\\a_{21}x_{1}+a_{22}x_{2}+\dots +a_{2n}x_{n}=b_{2}\\\dots \\a_{m1}x_{1}+a_{m2}x_{2}+\dots +a_{mn}x_{n}=b_{m}\\\end{cases}}}$$

где $a_{ij}$ и $b_{j}$ — произвольные числа, называемые коэффициентами при меременных $x_{1}, x_{2} \dots x_{n}$ и свободными членами. Матричная форма записи имеет вид $A = XB$, где

$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{pmatrix}$ — матрица коэффициентов при неизвестных,

$X = \begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{pmatrix}$ — матрица из неизвестных системы,

$B =
\begin{pmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{pmatrix}$ — матрица из свободных членов.

Решением системы `m` линейных уравнений с `n` переменными называют упорядоченный набор чисел, при подстановке которых в каждое уравнение системы вместо соответствующих переменных получают верное равенство. Как доказывает <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9A%D1%80%D0%BE%D0%BD%D0%B5%D0%BA%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%9A%D0%B0%D0%BF%D0%B5%D0%BB%D0%BB%D0%B8">Теорема Кронекера-Капелли</a>, СЛУ могут иметь одно решение, бесконечное множество решений, так и не иметь решения.

Рассмотрим случай, когда система имеет единственное решение. Это значит, что матрицв системы невырожднная, т.е. ее определитель не равен нулю, и эту систему можно решать по правилу <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0">Крамера</a> или методом обратной матрицы.

${\displaystyle {\begin{cases}3x_{1}-x_{2}+x_{3}=5\\
x_{1}-x_{2}-x_{3}=3\\
5x_{1}-3x_{2}-x_{3}=10\\\end{cases}}}$

Для решения системы воспользуемся функцией <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html">numpy.linalg.solve</a>. Функция принимает два параметра:
 - матрица коэффициентов перед переменными
 - вектор свободных членов

In [28]:
A = np.array([[3, -1, 1], 
              [1, -1, 1],
              [5, -3, -1,]])

B = np.array([3, 11, 8])

X = np.linalg.solve(A, B)

for i, x in enumerate(X, 1):
    print(f'x{i} = {x:.2f}')

x1 = -4.00
x2 = -10.75
x3 = 4.25


Определитель основной матрицы системы не равен нулю, мы получили единственное решение, хотя и не целочисленное.

In [29]:
np.linalg.det(A)

7.999999999999998

### Решение системы линейных уравнений $AX = B$ методом обратной матрицы

Для этого:
   1. вычислим определитель матрицы $A$. Если определитель равен нулю, то конец решения. Система имеет бесконечное множество решений.
   2. при определителе отличном от нуля, через алгебраические дополнения находится обратная матрица $A^{-1}$.
   3. вектор решения $X = \{x_{1}, x_{2} \dots x_{n}\}$ получается умолжением обратной матрицы на вектор результата $B$.

__Решить СЛУ методом обратной матрицы__

${\displaystyle{\begin{cases}2x_{1}-x_{2}-2x_{3}=-3\\
x_{1}-2x_{2}+x_{3}=5\\
3x_{1}+x_{2}-x_{3}=0\\\end{cases}}}$

In [34]:
A = np.array([[2, 1, -2], 
              [1, -2, 1],
              [3, 1, -1,]])

B = np.array([-3, 5, 0])

det = np.linalg.det(A)
if det == 0:
    print('Система имеет бесконечное множество решений, \
           определитель матрицы равен 0')
else:
    AI = np.linalg.inv(A)
    X = np.dot(AI, B)
    print(f'Решение системы {X}')

Решение системы [ 1. -1.  2.]


### Решение системы линейных уравнений $AX = B$ с использованием метода Крамера

Если определитель матрицы системы не равен нулю, ее можно решить по <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0">правилу Крамера</a>. Для этого находят определитель матрицы системы и делят на него определители, полученные заменой $i$-го столбца матрицы системы на столбец свободных членов. Эти отношения и будуи составлять решение системы. Оно будет единственным.

__Решить СЛУ методом Крамера__

${\displaystyle{\begin{cases}2x_{1}-x_{2}-2x_{3}=-3\\
x_{1}-2x_{2}+x_{3}=5\\
3x_{1}+x_{2}-x_{3}=0\\\end{cases}}}$

In [40]:
det = np.linalg.det(A)
if det == 0:
    print('определитель матрицы равен 0, \
          система имеет бесконечное множество решений')
else:
    s0, s1, s2 = A[:,0], A[:,1], A[:,2]
    a1 = np.column_stack((B, s1, s2))
    a2 = np.column_stack((s0, B, s2))
    a3 = np.column_stack((s0, s1, B))
    X = [d / det for d in map(np.linalg.det, (a1, a2, a3))]
    print(f'Решение системы {X}')

Решение системы [0.9999999999999996, -1.0, 2.0000000000000004]


Рассмотрим пример системы, которая имеет бесконечное множество решений.

### Этапы решения

  1. Найти определитель матрицы системы
  2. Если он не равен нулю, вывести решения с помошью `np.linalg.solve(A, B)`
  3. Иначе сравниваем ранги расширенной и основной матриц системы и используем <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9A%D1%80%D0%BE%D0%BD%D0%B5%D0%BA%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%9A%D0%B0%D0%BF%D0%B5%D0%BB%D0%BB%D0%B8">теорему Кронекера-Капелли</a>.
  
__Решить СЛУ__

${\displaystyle{\begin{cases}x_{1}+2x_{2}-x_{3}=7\\
2x_{1}-3x_{2}+x_{3}=3\\
4x_{1}+x_{2}-x_{3}=16\\\end{cases}}}$

In [63]:
A = np.array([[1, 2, -1], 
              [2, -3, 1],
              [4, 1, -1,]])

B = np.array([7, 3, 16])

det = np.linalg.det(A)

B1 = B.reshape((1, -1)) # B[np.newaxis, :]
AB = np.vstack((A, B1))

if det:
    X = np.linalg.solve(A, B)
    print('Единственное решение', X)
else:
    rank_a = np.linalg.matrix_rank(A) 
    rank_ab = np.linalg.matrix_rank(AB) 
    if rank_a == rank_ab:
        print('Система имеет бесконечное множество \
                               решений и частное', X)
    else:
        print('Система не имеет решений')

Система не имеет решений


# Элементы аналитической геометрии

## Векторы на плоскости и в пространстве. Операции над векторами.

Вектором на плостости и в пространстве называютмножество сонаправленных отрезков, имеющих одиноковую длину. Обозначают векторы малыми латинскими буквами со стрелкой ${\vec {a}}$. Если даны координаты начала и конца вектора, то чтобы найти координаты вектора, нужно из координат конца вычесть координаты начала. Если $A = (x_{1};y_{1}), B = (x_{2};y_{2})$, то ${\overrightarrow {AB}} = (x_{2}-x_{1};y_{2}-y_{1})$, а длина вектора $|{\overrightarrow  {AB}}| = |AB| = {\sqrt {(x_{2}-x_{1})^{2}+(y_{2}-y_{1})^{2}}}$.

Векторы линейно зависимые, если один из них можно представить как линейную комбинацию других.

### Примеры решений

#### 1. Даны вектор $a(5;1)$ и точка $A(-2;3)$. Найти координаты точки $B$, такой, что ${\vec {a}} = AB$

In [67]:
a = np.array([5, 1])
A = np.array([-3, 3])
B = a + A; B

array([2, 4])

#### 2. Найти вектор — результат векторного произведения векторов $a = (1;3;-1), b = (2;-2;1)$ и его длину.

Запишем вектор ${\vec {c}}$ через разлодение по базисным ортам $i, j, k$ и найдем его длину с помощью функции `np.linalg.norm`.

${\vec {c}} = {\displaystyle [{\vec {a}},\;{\vec {b}}]={\begin{vmatrix}\mathbf {i} &\mathbf {j} &\mathbf {k} \\a_{x}&a_{y}&a_{z}\\b_{x}&b_{y}&b_{z}\end{vmatrix}}}$

In [96]:
a = np.array([1, 3, -1])
b = np.array([2, -2, 1])
ab = np.vstack((a, b))

i, j, k = [ab[:,x] for x in range(3)]

a1 = np.column_stack((j, k))
a2 = np.column_stack((i, k))
a3 = np.column_stack((i, j))

c = [*map(np.linalg.det, (a1, a2, a3))]

print('c = ({:.1f})i + ({:.1f})j + ({:.1f})k\n\
Длина векторного произведения n = {}'.format(*c, np.linalg.norm(c)))

c = (1.0)i + (3.0)j + (-8.0)k
Длина векторного произведения n = 8.602325267042625


#### 3. Определить, будут ли линейно зависимы системы веторов:
    а) (1; 1; 4; 2), (-3; -1; 3; 4), (1; -1; -2; 4)
    б) (1; -1; -2; 4), (0; 2; 6; -2), (-3; -1; 3; 4), (-1; 0; -4; -7)

In [98]:
A = np.array([[1, 1, 4, 2],
              [-3, -1, 3, 4],
              [1, -1, -2, 4]])
A = A.T # транспонирование матрицы A
rank = np.linalg.matrix_rank(A)
k = A.shape[1]
if rank == k:
    print('Линейно независимы')
else:
    print('Линейно зависимы')

Линейно независимы


In [100]:
def lin_ind(a: list) -> None:
    A = a.T
    rank = np.linalg.matrix_rank(A)
    k = A.shape[1]
    if rank == k:
        print('Линейно независимы')
    else:
        print('Линейно зависимы')

A = np.array([[1, -1, -2, 4],
              [0, 2, 6, -2],
              [-3, -1, 3, 4],
              [-1, 0, -4, -7]])
lin_ind(A)

Линейно зависимы


#### 4. Определить, является ли система векторов (-1; 0; -4; -7), (1; 1; 4; 2), (-3; -1; 3; 4), (1; -2; -2; 4), (0, 2; 6; -2) линейно независимой

Определим, является ли система векторов ${\vec {a_{1}}}, {\vec {a_{2}}}, {\vec {a_{3}}}, {\vec {a_{4}}}, {\vec {a_{5}}}$ линейно зависимой или нет. Для этого составим линейную комбинацию $\alpha_{1}{\vec {a_{1}}} + \alpha_{2}{\vec {a_{2}}} + \alpha_{3}{\vec {a_{3}}} + \alpha_{4}{\vec {a_{4}}} + \alpha_{5}{\vec {a_{5}}}$. Подставим числовые значения векторов и приравляем линейную комбинацию к нулевому вектору (0; 0; 0; 0; 0).

В результате мы получим однородную систему линйеных уравнений. Если эта система имеет лишь одно решение, то веторы линейно независимы. Если решений бесконечно много, то векторы линейно зависимы.

СЛАУ можно решить разными способами. В примере ниже реализован <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%93%D0%B0%D1%83%D1%81%D1%81%D0%B0">метод Гаусса</a>.

In [114]:
def gauss_elimin(a: np.array, b: np.array) -> np.array:
    n = len(b)
    for k in range(n-1):
        for i in range(k+1, n):
            if a[i, k] != 0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]
        for k in range(n-1, -1, -1):
            b[k] = (b[k] - np.dot(a[k, k+1:n], b[k+1:n])) / a[k, k]
    return b

a = np.array([[-1, 0, -4, -7], [1, 1, 4, 2], [-3, -1, 3, 4], [1, -2, -2, 4], [0, 2, 6, -2]])
b = np.array([0, 0, 0, 0])

gauss_elimin(a, b)

array([0, 0, 0, 0])

В результате работы программы получаем нулевой вектор, следовательно система линейно зависима.

#### 5. Доказать, что векторы (3; 4; 3), (-2; 3; 1), (4; -2; 3) образуют базис и найти координаты вектора (-17; 18; -7) в этом базисе

Разберем упрощенный вариант проверки, касающийся квадратных матриц, для которых числовой характеристикой является не только ранг, но и определитель. Вспомним, что понижение ранга квадратной матрицы приводит к ее выражденности (то есть определитель такой матрицы будет равен нулю). Поэтому для ответа на вопрос о линейной зависимости трех векторов в трехмерном пространстве можно просто подсчитать значение определителя, составленного из координат этих векторов. Если он не ноль, то вектора линейно независимые.

In [117]:
b = np.array([-17, 18, -7])
a = np.array([[3, 4, 3], [-2, 3, 1], [4, -2, 3]])
a = a.T
det = np.linalg.det(a)
det

49.000000000000014

Следовательно, матрица является невырожденной и ее ранг равен трем. Поэтому векторы линейно независимы и образуют базис трехмерного пространства. Полученная система линейных уравнений является неоднородной. Основная матрица этой системы имеет ранг, равный трем, что совпадает с количеством переменных в системе. Поэтому системя является определенной, то есть имеет единственное решение.

In [118]:
np.linalg.solve(a, b)

array([ 1.,  2., -4.])

Вектора в базисе, состоящем из векторов (3; 4; 3), (-2; 3; 1), (4; -2; 3), имеет координаты (1; 2; -4)

#### 6. Построить ортоганальный базис на векторах $a_{1} = (3; 4; 3), a_{2} = (-2; 3; 1), a_{3} = (4; -2; 3)$ 

От системы векторов ${a}_i$ перейдем к системе ${a}_i^{*}$, в которой все векторы попарно ортогональны при всех $i$ от 1-го до 3-х следующим образом. Возьмем ${a}_1 = {a}_1^{*}, {a}_2 = a_2 + {a}_1^{*} \mu$, найдем $\mu$, умножив скалярно обе части последнего на ${a}_1$, получим ${\mu}=-\frac{(a_{1}, a_{2})} {(a_{1}, a_{1})}$, рассуждая аналогично получим ${a}_3^{*} = a_3 + {a}_1^{*} \mu + {a}_2^{*} \beta$, где ${\mu}=-\frac{(a_{3}, a_{1})} {(a_{1}, a_{1})}, {\beta}=-\frac{(a_{3}, {a}_2^{*})} {({a}_2^{*}, {a}_2^{*})}$.

Процесс посторения ортогональнога базиса называют ортогонализацией.

Система векторов ${a}_i^{*}$ обозначена как система ${b}_i$ в коде решения.

In [129]:
def mu(x: np.array, y: np.array) -> np.array:
    return -np.dot(x, y) / np.dot(x, x)

a1 = np.array([3, 4, 3])
a2 = np.array([-2, 3, 1])
a3 = np.array([4, -2, 3])

b1 = a1
b2 = a2 + a1 * mu(a1, a2)
b3 = a3 + a1 * mu(a1, a3) + b2 * mu(b2, a3)

k = np.dot(b1, b2)
i = np.dot(b3, b2)
f = np.dot(b1, b3)

print('Ортогональный базис', b1, b2, b3, \
      '\nОртонормированный базис', b1 / len(b1), b2 / len(b2), b3 / len(b3), \
      '\nСкалярные произведения', k, i, f, sep='\n')

Ортогональный базис
[3 4 3]
[-2.79411765  1.94117647  0.20588235]
[-0.62025316 -1.1164557   2.10886076]

Ортонормированный базис
[1.         1.33333333 1.        ]
[-0.93137255  0.64705882  0.06862745]
[-0.20675105 -0.3721519   0.70295359]

Скалярные произведения
-6.661338147750939e-16
-1.3322676295501878e-15
0.0


Последние три числа можно считать равными нулю.

## Прямые на плоскости в постранстве

Прямая на плоскости в пространстве задается линейным уравнением, то есть уравнением, в которое переменные $x, y$ входят в степени не больше первой. Существуют различные виды уравнений, задающих прямую линию на плоскости:
   - уравнение прямой, проходящей через 2 точки $\frac{x - {x}_0} {{x}_1 - {x}_0}=\frac{y - {y}_0} {{y}_1 - {y}_0}$;
   - уравнение прямой через угловой коэффициент $y = kx + b$;
   - общее уравнение прямой $ax + by +c = 0$;
   - вектор перпендикулярный прямой, нормальный вектор прямой ${\vec {n}} = (a; b)$;
   - вектор параллельной прямой, направляющий вектор прямой ${\vec {p}} = (-b; a)$;

#### 7. Написать уравнение прямой, проходящей через две заданные точки $M_{1} = (5, 3), M_{2} = (-2, 4)$. Представить это уравнение через угловой коэффициент, в общем виде, найти координаты направляющего и нормального векторов.

In [152]:
x1, y1 = 5., 3.
x2, y2 = -2., 4.

k = (y1 - y2) / (x1 - x2)
b = y2 - k * x2

print('Уравнение прямой, проходящей через точки M1 = (5, 3), M2 = (-2, 4),',
      f'y = {k:.2f} * x + {b:.2f}',
      f'Угловой коэффициент {k:.2f}',
      sep='\n'
     )
print(f'Перенесем все в одну сторону и получим общее уравнение прямой линии: {-k:.2f} * x + y + ({-b:.2f}) = 0',
      f'Направляющий вектор имеет координаты ({-k:.2f}, 1.0)',
      f'Нормальный вектор имеет координаты (1.0, {k:.2f})',
      sep='\n'
     )

Уравнение прямой, проходящей через точки M1 = (5, 3), M2 = (-2, 4),
y = -0.14 * x + 3.71
Угловой коэффициент -0.14
Перенесем все в одну сторону и получим общее уравнение прямой линии: 0.14 * x + y + (-3.71) = 0
Направляющий вектор имеет координаты (0.14, 1.0)
Нормальный вектор имеет координаты (1.0, -0.14)


#### 8. Найти угловые коэффициенты прямых, параллельных и перепендикулярных данной  $2x + 4y - 3 = 0$

Выразим из уравнения $y$, найдем угловой коэффициент $k$. У прямых, параллельных данной, угловой коэффициент равен $k_{1} = k$. А у перепендикулярных данной $k_{2} = -\frac{1}k$.

In [154]:
a, b, c = 2., 4., -3.
k1 = -a / b
k2 = -1 / k1

print(f'Угловой коэффициент прямых, параллельных прямой 2x + 4y - 3 = 0 равен {k1}',
      f'Угловой коэффициент прямых, перпендикулярных данной прямой равен {k2}', sep = '\n')

Угловой коэффициент прямых, параллельных прямой 2x + 4y - 3 = 0 равен -0.5
Угловой коэффициент прямых, перпендикулярных данной прямой равен 2.0
