In [2]:
import math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## ОПЕРАЦИИ НАД МАТРИЦАМИ И ИХ СВОЙСТВА

### Возведение матрицы в степень

Возвести $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\ 
\end{pmatrix}
\end{equation*}$ в третью степень

In [8]:
A = np.array([[1, 3], [2, 4]])
np.linalg.matrix_power(A, 3)

array([[ 37,  81],
       [ 54, 118]])

### Транспонирование матрицы

Транспонировать матрицу $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\ 
\end{pmatrix}
\end{equation*}$

In [7]:
A.transpose()

array([[1, 2],
       [2, 3]])

Вычислить значения многочлена $F(x) = 2x^3 - x + 5$ от матрицы $\begin{equation*}
A = 
\begin{pmatrix}
-1 & 2 \\
0 & 2 \\ 
\end{pmatrix}
\end{equation*}$

In [9]:
A = np.array([[-1, 0], [2, 2]])
np.linalg.matrix_power(A, 3) - A + 5

array([[ 5,  5],
       [ 9, 11]])

Вычислить определитель матрицы $\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 & 3 & 4 \\
2 & 1 & 3 & 4 \\ 
3 & 1 & 2 & 4 \\
4 & 3 & 2 & 1 \\
\end{pmatrix}
\end{equation*}$

In [14]:
A = np.array([[1, 2, 3, 4], 
              [2, 1, 3, 4],
              [3, 1, 2, 4],
              [4, 3, 2, 1]])
np.linalg.det(A)

-30.000000000000004

Вычислить обратную матрицу $\begin{equation*}
A = 
\begin{pmatrix}
1 & -1 & 1 \\
2 & 1 & 1 \\ 
1 & 1 & 2 \\
\end{pmatrix}
\end{equation*}$

In [17]:
A = np.array([[1, -1, 1], 
              [2, 1, 1],
              [1, 1, 2]])

np.linalg.inv(A)

array([[ 0.2,  0.6, -0.4],
       [-0.6,  0.2,  0.2],
       [ 0.2, -0.4,  0.6]])

Решить матричное уравнение $A X = B$

$\begin{equation*}A = 
\begin{pmatrix}
3 & 1 \\
-3 & 1 \\ 
\end{pmatrix}
\end{equation*}$,
$\begin{equation*}B = 
\begin{pmatrix}
9 & 5 \\
-3 & -1 \\ 
\end{pmatrix}
\end{equation*}$

Матрицу `X` находим путем произведения обратной матрицы $A^-1$ и $B$

In [18]:
A = np.array([[3, 1], 
              [-3, 1]])

B = np.array([[9, 5], 
              [-3, -1]])

np.dot(np.linalg.inv(A), B)

array([[2., 1.],
       [3., 2.]])

Вычислить ранг матрицы $\begin{equation*}
A = 
\begin{pmatrix}
0 & -1 & 3 & 0 & 2 \\
2 & -4 & 1 & 5 & 3 \\ 
-4 & 5 & 7 & -10 & 0 \\
-2 & 1 & 8 & -5 & 3 \\
\end{pmatrix}
\end{equation*}$

In [21]:
A = np.array([[0, -1, 3, 0, 2], 
              [2, -4, 1, 5, 3],
              [-4, 5, 7, -10, 0],
              [-2, 1, 8, -5, 3]])

np.linalg.matrix_rank(A)

2

### СИСТЕМЫ ЛИНЕЙНЫХ УРАВНЕНИЙ (СЛУ)

$${\displaystyle {\begin{cases}a_{11}x_{1}+a_{12}x_{2}+\dots +a_{1n}x_{n}=b_{1}\\a_{21}x_{1}+a_{22}x_{2}+\dots +a_{2n}x_{n}=b_{2}\\\dots \\a_{m1}x_{1}+a_{m2}x_{2}+\dots +a_{mn}x_{n}=b_{m}\\\end{cases}}}$$

где $a_{ij}$ и $b_{j}$ — произвольные числа, называемые коэффициентами при меременных $x_{1}, x_{2} \dots x_{n}$ и свободными членами. Матричная форма записи имеет вид $A = XB$, где

$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{pmatrix}$ — матрица коэффициентов при неизвестных,

$X = \begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{pmatrix}$ — матрица из неизвестных системы,

$B =
\begin{pmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{pmatrix}$ — матрица из свободных членов.

Решением системы `m` линейных уравнений с `n` переменными называют упорядоченный набор чисел, при подстановке которых в каждое уравнение системы вместо соответствующих переменных получают верное равенство. Как доказывает <a href="https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9A%D1%80%D0%BE%D0%BD%D0%B5%D0%BA%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%9A%D0%B0%D0%BF%D0%B5%D0%BB%D0%BB%D0%B8">Теорема Кронекера-Капелли</a>, СЛУ могут иметь одно решение, бесконечное множество решений, так и не иметь решения.

Рассмотрим случай, когда система имеет единственное решение. Это значит, что матрицв системы невырожднная, т.е. ее определитель не равен нулю, и эту систему можно решать по правилу <a href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0">Крамера</a> или методом обратной матрицы.

${\displaystyle {\begin{cases}3x_{1}-x_{2}+x_{3}=5\\
x_{1}-x_{2}-x_{3}=3\\
5x_{1}-3x_{2}-x_{3}=10\\\end{cases}}}$

Для решения системы воспользуемся функцией <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html">numpy.linalg.solve</a>. Функция принимает два параметра:
 - матрица коэффициентов перед переменными
 - вектор свободных членов

In [28]:
A = np.array([[3, -1, 1], 
              [1, -1, 1],
              [5, -3, -1,]])

B = np.array([3, 11, 8])

X = np.linalg.solve(A, B)

for i, x in enumerate(X, 1):
    print(f'x{i} = {x:.2f}')

x1 = -4.00
x2 = -10.75
x3 = 4.25


Определитель основной матрицы системы не равен нулю, мы получили единственное решение, хотя и не целочисленное.

In [29]:
np.linalg.det(A)

7.999999999999998

### Решение системы линейных уравнений $AX = B$ методом обратной матрицы

Для этого:
   1. вычислим определитель матрицы $A$. Если определитель равен нулю, то конец решения. Система имеет бесконечное множество решений.
   2. при определителе отличном от нуля, через алгебраические дополнения находится обратная матрица $A^{-1}$.
   3. вектор решения $X = \{x_{1}, x_{2} \dots x_{n}\}$ получается умолжением обратной матрицы на вектор результата $B$.

Hешить СЛУ методом обратной матрицы

${\displaystyle 
{\begin{cases}
2x_{1}-x_{2}-2x_{3}=-3\\
x_{1}-2x_{2}+x_{3}=5\\
3x_{1}+x_{2}-x_{3}=0\\\end
{cases}}}$

In [34]:
A = np.array([[2, 1, -2], 
              [1, -2, 1],
              [3, 1, -1,]])

B = np.array([-3, 5, 0])

det = np.linalg.det(A)

if det == 0:
    print('Система имеет бесконечное множество решений, \
           определитель матрицы равен 0')
else:
    AI = np.linalg.inv(A)
    X = np.dot(AI, B)
    print(f'Решение системы {X}')

Решение системы [ 1. -1.  2.]
